<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'EzzForum\Module'                        => __DIR__ . '/Module.php',
    'EzzForum\Controller\SkeletonController' => __DIR__ . '/src/EzzForum/Controller/SkeletonController.php',
    'EzzForumTest\Framework\TestCase'        => __DIR__ . '/tests/EzzForum/Framework/TestCase.php',
    'EzzForumTest\SampleTest'                => __DIR__ . '/tests/EzzForum/SampleTest.php',
);