<?php

$title = $this->translate('Add new post');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
//echo $this->formCollection($form);

$form = $this->form;
$form->setAttribute('action', $this->url('create', array('action' => 'create')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('body'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();