<?php echo $this->translate('List of posts'); ?>
<table>
    <thead>
        <tr>
            <th><?php echo $this->translate("ID") ?></th>
            <th><?php echo $this->translate("Thread Body") ?></th>
            <th><?php echo $this->translate("Created Date") ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($paginator as $post):?>
            <tr>
                <td><?php echo $post->getId()?></td>
                <td><?php echo $post->getBody()?></td>
                
            </tr>        
        <?php endforeach; ?>
    </tbody>
</table>